#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: mcxiaoke
# @Date:   2015-08-12 23:02:46

from __future__ import print_function
import json
import shutil
from StringIO import StringIO
from fanfou import utils
import template

html = StringIO()


data = json.load(open('data/timeline.json', 'r'))
html.write(template.HEAD)
html.write(template.BODY_HEADER.format(
    u'<p id="title" class="title">饭否消息备份</p>'))
html.write(u'<div class="timeline">')
for it in data:
    pretty_date = utils.pretty_fanfou_date(it['created_at']).decode('utf8')
    html.write(u'<div class="status" id="st_{0}">'.format(it['id']))
    html.write(u'''<div class="st_meta">
        <span class="st_name">{0}</span>
        <span class="st_uid">(@{1})</span>
        <span class="st_time" data-time="{2}">{3}</span>
        </div>'''.format(it['user']['screen_name'],
                         it['user']['id'], it['created_at'], pretty_date))
    html.write(
        u'<span class="st_text">{0}</span>'.format(it['text']))
    html.write(u'</div>')
html.write(u'</div>')
html.write(template.BODY_FOOTER.format(
    u'''<p id="copyright" class="copyright">Generated by 
    <a href="https://github.com/mcxiaoke/pyfanfou">PyFanfou</a></p>'''))
# http://stackoverflow.com/questions/6048085/python-write-unicode-text-to-a-text-file
with open('data/index.html', 'w') as out:
    out.write(html.getvalue().encode('utf8'))
